### PR TITLE
Sync to en.cppreference.com version 201803011

### PR DESCRIPTION
**Pull request by badshah400**
Update man pages to the latest version of the [offline book](http://en.cppreference.com/w/Cppreference:Archives). Please feel free to let me know if there is anything else to be done. Thanks for your really useful project.

### CODE REVIEW

**Comment by jeaye** [comment]
Thanks for re-generating this! Looks like there's a bit of upkeep which we could do in order to improve the generation.

Are you up for adding `(since C++20)` and `(until C++20)` here: https://github.com/jeaye/stdman/blob/master/src/groff_highlight.hpp#L68 and regenerating this list: https://github.com/jeaye/stdman/blob/master/src/groff_section.hpp#L39

**Comment by badshah400** [comment]
Hmm, something seems off with commit 8e552d5: too many deletions and not that many additions.

**Comment by jeaye** [comment]
I was just thinking the same thing, looking at it. Let's revert that, do the generation with the new C++20 highlighting, and call this PR good. I/we can look further into that section list outside of this.

Thank you so much!

**Comment by jeaye** [comment]
Alright, excellent. All good on your end?

**Comment by jeaye** [comment]
Sure, feel free to look around. Honestly, my concern about it is that the command hasn't been run in a couple of years and it may not be all that's required to get a good list again. It's hacky to begin with and has likely been broken by small changes in the HTML since the original section generation.

**Comment by badshah400** [comment]
I think I will start afresh. I was using the full source from
http://en.cppreference.com/w/File:cppreference-doc-20180311.tar.xz
instead of just the html book
http://en.cppreference.com/w/File:html_book_20180311.tar.xz.
In principle the first should be ok too, but it seems there are minor white space and formatting issues with former. Let me refork and submit a better PR. Sorry for the trouble.

**Pull request closed without merging**
