### PR TITLE
Regenerate with v20201016 (from unofficial releases)

### PR DESCRIPTION
**Pull request by reverseila**
Man pages are regenerated with the HTML books from the [unofficial source](https://github.com/PeterFeicht/cppreference-doc) (mentioned by the [cppreferece](https://en.cppreference.com/w/Cppreference:Archives)) and not the
official one. The reason is that, the latest official release dates back to June 2019!

Notes from the release:

>  v20201016 Latest
>    - Update content from the website.
>    - Remove new ads (BuySellAds)

---

One problem with the generated files was that, there were a lot of trailing blanks in them. So I removed them with:

```sh
 find man ! -type d -exec sed -i'' 's/[[:blank:]]*$//' {} \;
```

Hopefully, that didn't create any unwanted result.

### CODE REVIEW

**Comment by jeaye** [comment]
Thanks!

**Comment by reverseila** [comment]
Urwlcm!

**Comment by Mick235711** [comment]
(Is there any plan and/or instructions for regenerating from v20211127? If this is as simple as download the release - put in `reference/en/cpp` - `make generate` - remove trailing blanks, probably I can help with a new PR too.)

**Comment by reverseila** [comment]
@Mick235711 I don't quite remember, but I just followed the instruction in the readme and, in the end, removed any trailing white spaces in the generated man pages. Please regenerate the new man pages, if that's what you want to do. That was what I did for the previous version.

**Pull request merged**
