### PR TITLE
Fix #39

### LINKED ISSUE #39: No manual entry for member functions
Hi, i have a problem when using stdman. 
I can only get man page of the class,
and get "no manual entry" message for all the member functions.
```
~$ man std::string::c_str
No manual entry for std::string::c_str
```

I refered to issue #22, and followed the **Troubleshooting** in **README** file.
still can not get it work. Could you help to check it?

-  os 
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
- the last few lines of man std::string
image
- files in install dir
```
~$ ls -ltr /usr/local/share/man/man3 | grep "std::string"
-rw-r--r-- 1 root root  534 Apr 11 22:04 std::hash(std::string_view,std::wstring_view,std::u16string_view,std::u32string_view).3.gz
-rw-r--r-- 1 root root  767 Apr 11 22:04 std::hash(std::string,std::wstring,std::u16string,std::u32string,std::pmr::string,.3.gz
-rw-r--r-- 1 root root 2603 Apr 11 22:04 std::string.3.gz
-rw-r--r-- 1 root root 2946 Apr 11 22:04 std::stringstream.3.gz
-rw-r--r-- 1 root root 2195 Apr 11 22:04 std::stringbuf.3.gz
-rw-r--r-- 1 root root  529 Apr 11 22:04 std::stringstream::operator=.3.gz
-rw-r--r-- 1 root root  319 Apr 11 22:04 std::stringstream::rdbuf.3.gz
-rw-r--r-- 1 root root  464 Apr 11 22:04 std::stringstream::swap.3.gz
```
- configure in .bashrc
```
~$ cat ~/.bashrc | tail -n 2
export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
export MANPATH=/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/man
```

### PR DESCRIPTION
**Pull request by prehistoric-penguin**
Cpprefenre have changed their wiki to add template in header part:
Previous format:

``` cpp
std::basic_string::find
```

Current format:

```cpp
std::basic_string<CharT,Traits,Allocator>::find
```

To remove the template with regex will fix the current break

### CODE REVIEW

**Comment by jeaye** [comment]
Thanks for the change! Would you mind doing one more generation, after adding `Categories`, `Hidden category`, and `Hidden categories` to the section list, similar to this manual addition? https://github.com/jeaye/stdman/blob/master/src/groff_section.hpp#L129

I see them showing up in the diff here, so they must be new:

* https://github.com/jeaye/stdman/pull/42/files#diff-3ac2eae84012a738a052fb9566c6861ebdd97eac0b7f1f4bed739ac1e85d6cbeR88
* https://github.com/jeaye/stdman/pull/42/files#diff-0827ddd16c3f9d48e7f32890ee7899b06f870d810a3e1813532d913ee546ae33R32

If you're not up for it, I can merge this, add the new sections, and then do another generation myself some time this week.

**Comment by prehistoric-penguin** [comment]
Thanks, I will follow up on your guides and commit the change latter.

I also suggest now we change the c++ version to c++17 since it's widely used today, what's your opinion?

**Comment by prehistoric-penguin** [comment]
I have added these new sections, could you please review it again.

**Comment by jeaye** [comment]
Thanks for the additional changes! Changing to C++17 is no problem, but we can do that in another PR.

**Pull request merged**
