### PR TITLE
configure: remove unnecessary code

### PR DESCRIPTION
**Pull request by wilhelmtell**
* remove the 'rm -f Makefile' line:  the sed line that follows that
   line truncates the file if it exists and creates it if it doesn't.
   there is no need to remove the file prior.

 * remove functions log_start() and log_end():  these functions are not
   used.

### CODE REVIEW

**Comment by jeaye** [comment]
Hi! Thanks for all of the PRs. No concerns for any of them except for this one.

We need the `rm -f Makefile`, since:

```bash
┌─(✓)[jeaye@oryx]─[~][23:38:04]
└──╼ echo foo > bar
┌─(✓)[jeaye@oryx]─[~][23:38:07]
└──╼ cat bar
foo
┌─(✓)[jeaye@oryx]─[~][23:38:09]
└──╼ echo spam > bar
-bash: bar: cannot overwrite existing file
```

**Comment by wilhelmtell** [comment]
Ah, I think that is because you have `set -o noclobber`.

    set -o |grep noclobber

would check for that. In that case, either

    sed ... >|Makefile

rather than

    sed ... >Makefile

would do the trick, forcing the overwrite, temporarily overriding the `noclobber` option. Or, indeed, the `rm -f Makefile` line.

**Comment by jeaye** [comment]
`sed ... >|Makefile` typically won't work on macOS. All of this leads to just having the `rm -f Makefile`. :smiley:

**Comment by wilhelmtell** [comment]
Sorry for the delay. I pushed an update with the `rm -f Makefile` line restored. Should I squash the commits (and force-push)?

**Comment by wilhelmtell** [comment]
Oh! >< sorry, I reverted the wrong lines >< I’ll fix when I’m home, sorry ><

**Comment by wilhelmtell** [comment]
Okay, should be good now.

At this point I‘m guessing it’s safe to say I should squash the commits in one (and force-push the branch)? 😆

**Comment by jeaye** [comment]
Sure, a squash would be good. Thanks!

**Comment by wilhelmtell** [comment]
Done!

**Pull request merged**
